// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuBNzxKThGJA6EfwyuQy3K4rcfNhbLziY',
    appId: '1:303535737035:web:7141adbe16a484b059f34e',
    messagingSenderId: '303535737035',
    projectId: 'smartshelter-29b27',
    authDomain: 'smartshelter-29b27.firebaseapp.com',
    storageBucket: 'smartshelter-29b27.appspot.com',
    measurementId: 'G-74942QXW3J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfIQd4zcsqFanA9DzNz2NhANDko8SrBEU',
    appId: '1:303535737035:android:52b11655cacb64d059f34e',
    messagingSenderId: '303535737035',
    projectId: 'smartshelter-29b27',
    storageBucket: 'smartshelter-29b27.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDggIwvKNvf9LRqHsINzQG67IekcThgmw',
    appId: '1:303535737035:ios:a9176bb493c635d459f34e',
    messagingSenderId: '303535737035',
    projectId: 'smartshelter-29b27',
    storageBucket: 'smartshelter-29b27.appspot.com',
    iosBundleId: 'com.example.smartAlacena',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDggIwvKNvf9LRqHsINzQG67IekcThgmw',
    appId: '1:303535737035:ios:a5cf01d851ce87ba59f34e',
    messagingSenderId: '303535737035',
    projectId: 'smartshelter-29b27',
    storageBucket: 'smartshelter-29b27.appspot.com',
    iosBundleId: 'com.example.smartAlacena.RunnerTests',
  );
}
